# Generated by Django 4.1.4 on 2022-12-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_id', models.IntegerField()),
                ('national_code', models.IntegerField(primary_key=True, serialize=False)),
                ('cigarette_status', models.BooleanField(null=True)),
                ('bed_time', models.CharField(max_length=15, null=True)),
                ('tidyness_status', models.CharField(max_length=15, null=True)),
                ('personal_type', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(default='user@test.com', max_length=254)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
