# Generated by Django 4.1.4 on 2022-12-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shared_room_id',
            field=models.IntegerField(default=0),
        ),
    ]
