# Generated by Django 4.1.4 on 2023-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInfo', '0002_user_shared_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
